# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=254)),
                ('industry', models.CharField(blank=True, max_length=254)),
                ('position', models.CharField(blank=True, max_length=254)),
                ('city_hq', models.CharField(blank=True, max_length=254)),
                ('num_employees', models.IntegerField(blank=True)),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
