# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=254)),
                ('company_name', models.CharField(max_length=254)),
                ('industry', models.CharField(max_length=254)),
                ('position', models.CharField(max_length=254)),
                ('city_headquarters', models.CharField(max_length=254)),
                ('num_employees', models.IntegerField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Registered at')),
            ],
        ),
    ]
